version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gym_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lordwolndemort0195
      POSTGRES_DB: crm_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: gym_bot
    restart: always
    depends_on:
      - db  # Бот не запустится, пока не поднимется база
    env_file:
      - .en
    environment:
      DB_FILE: "postgresql+asyncpg://postgres:lordwolndemort0195@db:5432/crm_db"
    volumes:
      - .:/app
      - ./logs:/app/logs

volumes:
  pg_data:
