"""add_fields_to_order

Revision ID: 1ec38623f34e
Revises: b3e1296c4826
Create Date: 2026-07-08 15:52:27.051566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec38623f34e'
down_revision: Union[str, Sequence[str], None] = 'b3e1296c4826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    columns = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("payment_orders")}
    if {"lesson_count", "days_to_add"}.issubset(columns):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_orders', sa.Column('lesson_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('payment_orders', sa.Column('days_to_add', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'days_to_add')
    op.drop_column('payment_orders', 'lesson_count')
    # ### end Alembic commands ###
