"""add_discipline_to_payment

Revision ID: 1f0f417c0b3b
Revises: a6def8ae7831
Create Date: 2026-07-15 20:21:27.422878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0f417c0b3b'
down_revision: Union[str, Sequence[str], None] = 'a6def8ae7831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    columns = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("payment_orders")}
    if "discipline" in columns:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_orders', sa.Column('discipline', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'discipline')
    # ### end Alembic commands ###
