"""allow_null_student_id_in_finance

Revision ID: 21ce4c23230f
Revises: f650c3395091
Create Date: 2026-07-14 09:17:08.804984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ce4c23230f'
down_revision: Union[str, Sequence[str], None] = 'f650c3395091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_orders', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('payment_orders_student_id_fkey'), 'payment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'payment_orders', 'students', ['student_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subscriptions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('subscriptions_student_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'students', ['student_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_student_id_fkey'), 'subscriptions', 'students', ['student_id'], ['id'])
    op.alter_column('subscriptions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'payment_orders', type_='foreignkey')
    op.create_foreign_key(op.f('payment_orders_student_id_fkey'), 'payment_orders', 'students', ['student_id'], ['id'])
    op.alter_column('payment_orders', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
