"""add_biometric_to_user

Revision ID: 86d7c9ea7073
Revises: 9bfe3092437f
Create Date: 2026-07-03 15:32:06.187072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d7c9ea7073'
down_revision: Union[str, Sequence[str], None] = '9bfe3092437f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_biometric_enabled', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_biometric_enabled')
    # ### end Alembic commands ###
