"""add_discipline_to_student

Revision ID: 9618481f5012
Revises: 1ec38623f34e
Create Date: 2026-07-08 18:39:12.076171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9618481f5012'
down_revision: Union[str, Sequence[str], None] = '1ec38623f34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('discipline', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'discipline')
    # ### end Alembic commands ###
