"""allow_null_student_id_in_finance

Revision ID: a6def8ae7831
Revises: 21ce4c23230f
Create Date: 2026-07-14 09:23:19.103251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6def8ae7831'
down_revision: Union[str, Sequence[str], None] = '21ce4c23230f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_orders', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('payment_orders_user_id_fkey'), 'payment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'payment_orders', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['user_id'])
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'payment_orders', type_='foreignkey')
    op.create_foreign_key(op.f('payment_orders_user_id_fkey'), 'payment_orders', 'users', ['user_id'], ['user_id'])
    op.alter_column('payment_orders', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
