"""auto_fix_columns

Revision ID: abf9d31d7a46
Revises: 7f725dd0b763
Create Date: 2026-04-15 14:45:51.848514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf9d31d7a46'
down_revision: Union[str, Sequence[str], None] = '7f725dd0b763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('subscription_expire_at', sa.DateTime(), nullable=True))
    op.drop_column('clubs', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('clubs', 'subscription_expire_at')
    # ### end Alembic commands ###
