"""add_tbank_payments

Revision ID: b3e1296c4826
Revises: 86d7c9ea7073
Create Date: 2026-07-08 15:24:00.673718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e1296c4826'
down_revision: Union[str, Sequence[str], None] = '86d7c9ea7073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Some older deployments already created these tables through the
    # compatibility payment migration. Keep this historical migration
    # idempotent when bringing that database onto the complete server history.
    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    if {"payment_orders", "subscriptions"}.issubset(existing_tables):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('amount_kopecks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_club_id'), 'payment_orders', ['club_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_student_id'), 'payment_orders', ['student_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('rebill_id', sa.String(length=50), nullable=True),
    sa.Column('amount_kopecks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('next_charge_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_club_id'), 'subscriptions', ['club_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_charge_at'), 'subscriptions', ['next_charge_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_student_id'), 'subscriptions', ['student_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_student_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_charge_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_club_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_student_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_club_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    # ### end Alembic commands ###
