"""add parent_phone

Revision ID: ba3c7c8999f8
Revises: ee4dd5a6834b
Create Date: 2026-02-25 13:43:16.111807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3c7c8999f8'
down_revision: Union[str, Sequence[str], None] = 'ee4dd5a6834b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.alter_column('students', 'parent_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'parent_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('students', 'parent_phone')
    # ### end Alembic commands ###
