"""add_frozen_at_to_student

Revision ID: f650c3395091
Revises: 9618481f5012
Create Date: 2026-07-11 21:14:13.569358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f650c3395091'
down_revision: Union[str, Sequence[str], None] = '9618481f5012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('frozen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'frozen_at')
    # ### end Alembic commands ###
