name: My_crm_bot

on:
  push:
    branches: [ master ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run test
        env:
          DB_FILE: sqlite+aiosqlite:///./test.db
          DB_PASSWORD: fake_password
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/my_crm_bot  
            git pull origin master
            pip install -r requirements.txt
            docker compose up -d --build
            docker image prune -f
